language: go

go:
  - "1.10.x"

addons:
  sonarcloud:
    organization: "lonegunmanb-github"
    token:
      secure: $SONAR_TOKEN

install:
  - go get github.com/golang/mock/gomock
  - cd $GOPATH/src/github.com/golang/mock
  - git checkout tags/v1.2.0
  - go install github.com/golang/mock/mockgen
  - cd $TRAVIS_BUILD_DIR
  - go get -t -v ./...
  - go generate ./...

script: go test -coverprofile=coverage.out github.com/lonegunmanb/varys/...

after_script:
  - sonar-scanner -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=lonegunmanb_varys -Dsonar.login=$SONAR_TOKEN -Dsonar.go.coverage.reportPaths=coverage.out -Dsonar.test.exclusions="**/*_test.go"